### ISSUE TITLE
Cant get it to work with angular and cordova whitelist

### ISSUE THREAD

**Issue by Strutsagget** [klarna/klarna-on-demand-js#10]
Hi

Im having problem get this to work with whitelisting klarna iframe.
Is there a ways to manually add the iframe and its url?

**Comment by Strutsagget** [comment]
So i think i sorted it out with the cordova-whitelist plugin and adding meta to index.html
 <meta http-equiv="Content-Security-Policy" content="default-src 'self' 'unsafe-inline' 'unsafe-eval' data: gap: https://ssl.gstatic.com http://localhost:* https://localhost:* ws://localhost:* *.klarna.com https://*.klarna.com />

**Comment by grozen** [comment]
It's best when issues solve themselves through the diligence of others :)
Can I mark this as closed, then?

**Comment by Strutsagget** [comment]
yeah its closed
